import torch
import matplotlib.pyplot as plt
from models.vae import VAE

def generate_random_digits():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # 1. Cargamos el modelo
    latent_dim = 20
    model = VAE(input_dim=784, latent_dim=latent_dim).to(device)
    model.load_state_dict(torch.load("checkpoints/vae_mnist.pth", weights_only=True))
    model.eval() # Modo evaluación (apaga gradientes)

    # 2. Muestreo Aleatorio (Ignoramos el Encoder)
    # Generamos 16 vectores de ruido a partir de una distribución Normal estándar N(0, I)
    with torch.no_grad():
        # Shape: [16 imágenes, 20 dimensiones]
        sample_z = torch.randn(16, latent_dim).to(device)
        
        # Pasamos el ruido solo por el Decoder
        generated_images = model.decoder(sample_z)
        
        # Redimensionamos de vectores de 784 a imágenes de 28x28
        generated_images = generated_images.view(16, 28, 28).cpu().numpy()

    # 3. Visualización
    fig, axes = plt.subplots(4, 4, figsize=(6, 6))
    for i, ax in enumerate(axes.flatten()):
        ax.imshow(generated_images[i], cmap='gray')
        ax.axis('off')
        
    plt.suptitle("Random Digits Generated by VAE with a latent space of 20 dimensions", fontsize=10)
    plt.tight_layout()
    #plt.show()
    # Save figure
    plt.savefig("results/random_digits_20dlatentspace.png", dpi=300)

if __name__ == "__main__":
    generate_random_digits()