import argparse
import math
import os
import json

import torch
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm

from models.loss import vae_loss
from models.vae import VAE
from utils.get_dataset import get_mnist_dataloaders
from utils.frey_face import get_frey_face_dataloaders


def gaussian_nll(z, mu, log_var):
    """
    Negative log-likelihood of z under q_phi(z|x) = N(mu, diag(exp(log_var))).

    During sleep phase, z comes from the prior and mu/log_var from the encoder
    on dreamed data. Minimizing this brings q_phi closer to the prior when x is
    generated by the decoder.
    """
    return 0.5 * torch.sum(
        math.log(2 * math.pi) + log_var + (z - mu).pow(2) / log_var.exp()
    )


def evaluate_elbo(model, data_loader, device, dataset='mnist'):
    """
    Mean negative ELBO on the dataset (same loss as train.py / vae_loss).

    Does not train; only monitors whether the combined model improves even though
    wake/sleep phases update different parts separately.
    """
    model.eval()
    total_loss = 0

    with torch.no_grad():
        for data, _ in data_loader:
            data = data.to(device)
            recon_batch, mu, log_var = model(data)
            loss, _, _ = vae_loss(recon_batch, data, mu, log_var, dataset=dataset) 
            total_loss += loss.item()

    model.train()
    return total_loss / len(data_loader.dataset)


def train_wake_sleep(dataset='mnist', latent_dim=20, epochs=50, batch_size=128,
                     lr=1e-3, sleep_batches_per_wake=1, save_metrics=True):
    """
    Train VAE with Wake-Sleep algorithm and record metrics during training.

    Args:
        dataset: 'mnist' or 'frey_face'
        latent_dim: Latent dimension
        epochs: Number of training epochs
        batch_size: Minibatch size
        lr: Learning rate
        sleep_batches_per_wake: Sleep updates per wake update
        save_metrics: Whether to save metrics

    Returns:
        dict: Training metrics
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load dataset
    if dataset == 'mnist':
        train_loader, test_loader = get_mnist_dataloaders(batch_size=batch_size)
        input_dim = 784
    elif dataset == 'frey_face':
        train_loader, test_loader = get_frey_face_dataloaders(batch_size=batch_size)
        input_dim = 560
    else:
        raise ValueError(f"Unknown dataset: {dataset}")

    print(
        f"Training Wake-Sleep on {dataset} (Nz={latent_dim}) for {epochs} epochs "
        f"on {device}"
    )

    model = VAE(input_dim=input_dim, dataset=dataset, latent_dim=latent_dim).to(device)

    # 1. Gather generative parameters based on the dataset
    if dataset == 'mnist':
        gen_params = model.decoder.parameters()
    elif dataset == 'frey_face':
        gen_params = (
            list(model.decoder_hidden.parameters()) + 
            list(model.dec_mu.parameters()) + 
            list(model.dec_log_var.parameters())
        )

    # 2. Separate optimizers for wake and sleep phases (Adagrad + Weight Decay)
    generative_optimizer = optim.Adagrad(
        gen_params, 
        lr=lr, 
        weight_decay=1e-4
    )
    
    recognition_optimizer = optim.Adagrad(
        list(model.encoder.parameters())
        + list(model.fc_mu.parameters())
        + list(model.fc_log_var.parameters()),
        lr=lr,
        weight_decay=1e-4
    )

    # Metrics tracking
    metrics = {
        'samples_evaluated': [],
        'train_loss': [],
        'test_loss': [],
    }

    model.train()
    total_samples_seen = 0
    pbar = tqdm(range(1, epochs + 1))

    for epoch in pbar:
        for data, _ in train_loader:
            data = data.to(device)
            current_batch_size = data.size(0)

            # WAKE PHASE: learn p_theta(x|z) with real data
            # q_phi(z|x) only does inference; its gradients do not propagate.
            with torch.no_grad():
                h = model.encoder(data)
                mu = model.fc_mu(h)
                log_var = model.fc_log_var(h)
                z = model.reparameterize(mu, log_var)

            generative_optimizer.zero_grad()
            # Decode based on the dataset
            if dataset == 'mnist':
                recon_batch = model.decoder(z)
                wake_loss = F.binary_cross_entropy(recon_batch, data, reduction="sum")
                
            elif dataset == 'frey_face':
                # Pass through the separated Frey Face decoder layers
                h_dec = model.decoder_hidden(z)
                recon_mu = model.dec_mu(h_dec)
                recon_log_var = model.dec_log_var(h_dec)
                
                sq_err = (recon_mu - data).pow(2)
                
                # Raw math
                wake_loss = 0.5 * torch.sum(recon_log_var + sq_err / recon_log_var.exp())

            wake_loss.backward()
            generative_optimizer.step()

            # SLEEP PHASE: learn q_phi(z|x) with fantasies from the generative model
            for _ in range(sleep_batches_per_wake):
                with torch.no_grad():
                    # 1. Sample z from the prior N(0, I)
                    z_prior = torch.randn(current_batch_size, latent_dim).to(device)
                    
                    # 2. Decode the prior into "dreamed" data based on the dataset
                    if dataset == 'mnist':
                        dreamed_probs = model.decoder(z_prior)
                        dreamed_x = torch.bernoulli(dreamed_probs)
                        
                    elif dataset == 'frey_face':
                        # Manually pass through the Frey Face decoder layers
                        h_dec = model.decoder_hidden(z_prior)
                        dreamed_mu = model.dec_mu(h_dec)
                        dreamed_log_var = model.dec_log_var(h_dec)
                        
                        # Sample continuous dreamed_x using the reparameterization trick
                        std = torch.exp(0.5 * dreamed_log_var)
                        eps = torch.randn_like(std)
                        dreamed_x = dreamed_mu + eps * std

                recognition_optimizer.zero_grad()
                h_sleep = model.encoder(dreamed_x)
                mu_sleep = model.fc_mu(h_sleep)
                log_var_sleep = model.fc_log_var(h_sleep)
                # Adjust q_phi to assign high density to the z that generated the dream.
                sleep_loss = gaussian_nll(z_prior, mu_sleep, log_var_sleep)
                sleep_loss.backward()
                recognition_optimizer.step()

            total_samples_seen += current_batch_size

        # Evaluate on test set
        train_neg_elbo = evaluate_elbo(model, train_loader, device, dataset=dataset)
        test_neg_elbo = evaluate_elbo(model, test_loader, device, dataset=dataset)

        metrics['samples_evaluated'].append(total_samples_seen)
        metrics['train_loss'].append(train_neg_elbo)
        metrics['test_loss'].append(test_neg_elbo)

        pbar.set_description(
            f"Epoch {epoch}/{epochs} | "
            f"train NELBO: {train_neg_elbo:.4f} | test NELBO: {test_neg_elbo:.4f}"
        )

    os.makedirs("checkpoints", exist_ok=True)
    checkpoint_path = f"checkpoints/wake_sleep_{dataset}_{latent_dim}d.pth"
    torch.save(model.state_dict(), checkpoint_path)
    print(f"Wake-Sleep model saved to {checkpoint_path}")

    # Save metrics
    if save_metrics:
        metrics_path = f"results/metrics/wake_sleep_{dataset}_{latent_dim}d_metrics.json"
        os.makedirs("results/metrics", exist_ok=True)
        with open(metrics_path, 'w') as f:
            json.dump(metrics, f)
        print(f"Metrics saved to {metrics_path}")

    return metrics


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train a Wake-Sleep model with metrics tracking."
    )
    parser.add_argument(
        "--dataset",
        type=str,
        default="mnist",
        choices=["mnist", "frey_face"],
        help="Dataset to use.",
    )
    parser.add_argument(
        "--latent_dim",
        type=int,
        default=20,
        help="Dimensionality of the latent space.",
    )
    parser.add_argument("--epochs", type=int, default=50, help="Training epochs.")
    parser.add_argument(
        "--batch_size",
        type=int,
        default=100,
        help="Minibatch size.",
    )
    parser.add_argument("--lr", type=float, default=0.01, help="Adam learning rate.")
    parser.add_argument(
        "--sleep_batches_per_wake",
        type=int,
        default=1,
        help="Number of sleep updates after each wake update.",
    )
    args = parser.parse_args()
    train_wake_sleep(**vars(args))
